#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ApneaDiscipline type as an enum
    /// </summary>
    public enum ApneaDiscipline : byte
    {
        ConstantWeightWithFins = 0,
        ConstantWeightWithBifins = 1,
        ConstantWeightWithoutFins = 2,
        DynamicWithFins = 3,
        DynamicWithBifins = 4,
        DynamicWithoutFins = 5,
        FreeImmersion = 6,
        NoLimit = 7,
        SpeedEnduranceApnea = 8,
        StaticApnea = 9,
        VariableWeight = 10,
        Invalid = 0xFF


    }
}

