#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile AutolapTrigger type as an enum
    /// </summary>
    public enum AutolapTrigger : byte
    {
        Time = 0,
        Distance = 1,
        PositionStart = 2,
        PositionLap = 3,
        PositionWaypoint = 4,
        PositionMarked = 5,
        Off = 6,
        AutoSelect = 13,
        Invalid = 0xFF


    }
}

