#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile CardioExerciseName type as a class
    /// </summary>
    public static class CardioExerciseName 
    {
        public const ushort BobAndWeaveCircle = 0;
        public const ushort WeightedBobAndWeaveCircle = 1;
        public const ushort CardioCoreCrawl = 2;
        public const ushort WeightedCardioCoreCrawl = 3;
        public const ushort DoubleUnder = 4;
        public const ushort WeightedDoubleUnder = 5;
        public const ushort JumpRope = 6;
        public const ushort WeightedJumpRope = 7;
        public const ushort JumpRopeCrossover = 8;
        public const ushort WeightedJumpRopeCrossover = 9;
        public const ushort JumpRopeJog = 10;
        public const ushort WeightedJumpRopeJog = 11;
        public const ushort JumpingJacks = 12;
        public const ushort WeightedJumpingJacks = 13;
        public const ushort SkiMoguls = 14;
        public const ushort WeightedSkiMoguls = 15;
        public const ushort SplitJacks = 16;
        public const ushort WeightedSplitJacks = 17;
        public const ushort SquatJacks = 18;
        public const ushort WeightedSquatJacks = 19;
        public const ushort TripleUnder = 20;
        public const ushort WeightedTripleUnder = 21;
        public const ushort Elliptical = 22;
        public const ushort Spinning = 23;
        public const ushort PolePaddleForwardWheelchair = 24;
        public const ushort PolePaddleBackwardWheelchair = 25;
        public const ushort PoleHandcycleForwardWheelchair = 26;
        public const ushort PoleHandcycleBackwardWheelchair = 27;
        public const ushort PoleRainbowWheelchair = 28;
        public const ushort DoublePunchForwardWheelchair = 29;
        public const ushort DoublePunchDownWheelchair = 30;
        public const ushort DoublePunchSidewaysWheelchair = 31;
        public const ushort DoublePunchUpWheelchair = 32;
        public const ushort SitSkiWheelchair = 33;
        public const ushort SittingJacksWheelchair = 34;
        public const ushort PunchForwardWheelchair = 35;
        public const ushort PunchDownWheelchair = 36;
        public const ushort PunchSidewaysWheelchair = 37;
        public const ushort PunchUpWheelchair = 38;
        public const ushort PunchBagWheelchair = 39;
        public const ushort PoleDdFfUuWheelchair = 40;
        public const ushort ButterflyArmsWheelchair = 41;
        public const ushort Punch = 42;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

