#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdDisplayType type as an enum
    /// </summary>
    public enum ExdDisplayType : byte
    {
        Numerical = 0,
        Simple = 1,
        Graph = 2,
        Bar = 3,
        CircleGraph = 4,
        VirtualPartner = 5,
        Balance = 6,
        StringList = 7,
        String = 8,
        SimpleDynamicIcon = 9,
        Gauge = 10,
        Invalid = 0xFF


    }
}

