#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile FlyeExerciseName type as a class
    /// </summary>
    public static class FlyeExerciseName 
    {
        public const ushort CableCrossover = 0;
        public const ushort DeclineDumbbellFlye = 1;
        public const ushort DumbbellFlye = 2;
        public const ushort InclineDumbbellFlye = 3;
        public const ushort KettlebellFlye = 4;
        public const ushort KneelingRearFlye = 5;
        public const ushort SingleArmStandingCableReverseFlye = 6;
        public const ushort SwissBallDumbbellFlye = 7;
        public const ushort ArmRotations = 8;
        public const ushort HugATree = 9;
        public const ushort FaceDownInclineReverseFlye = 10;
        public const ushort InclineReverseFlye = 11;
        public const ushort RearDeltFlyWheelchair = 12;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

