#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile FrenchGradingScale type as an enum
    /// </summary>
    public enum FrenchGradingScale : byte
    {
        _1 = 0,
        _2 = 1,
        _3 = 2,
        _4a = 3,
        _4b = 4,
        _4c = 5,
        _5a = 6,
        _5b = 7,
        _5c = 8,
        _6a = 9,
        _6aPlus = 10,
        _6b = 11,
        _6bPlus = 12,
        _6c = 13,
        _6cPlus = 14,
        _7a = 15,
        _7aPlus = 16,
        _7b = 17,
        _7bPlus = 18,
        _7c = 19,
        _7cPlus = 20,
        _8a = 21,
        _8aPlus = 22,
        _8b = 23,
        _8bPlus = 24,
        _8c = 25,
        _8cPlus = 26,
        _9a = 27,
        _9aPlus = 28,
        _9b = 29,
        Invalid = 0xFF


    }
}

