#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile IndoorBikeExerciseName type as a class
    /// </summary>
    public static class IndoorBikeExerciseName 
    {
        public const ushort AirBike = 0;
        public const ushort AssaultBike = 1;
        public const ushort StationaryBike = 3;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

