#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile LegCurlExerciseName type as a class
    /// </summary>
    public static class LegCurlExerciseName 
    {
        public const ushort LegCurl = 0;
        public const ushort WeightedLegCurl = 1;
        public const ushort GoodMorning = 2;
        public const ushort SeatedBarbellGoodMorning = 3;
        public const ushort SingleLegBarbellGoodMorning = 4;
        public const ushort SingleLegSlidingLegCurl = 5;
        public const ushort SlidingLegCurl = 6;
        public const ushort SplitBarbellGoodMorning = 7;
        public const ushort SplitStanceExtension = 8;
        public const ushort StaggeredStanceGoodMorning = 9;
        public const ushort SwissBallHipRaiseAndLegCurl = 10;
        public const ushort ZercherGoodMorning = 11;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

