#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile MoveExerciseName type as a class
    /// </summary>
    public static class MoveExerciseName 
    {
        public const ushort ArchAndCurl = 0;
        public const ushort ArmCirclesWithBallBandAndWeight = 1;
        public const ushort ArmStretch = 2;
        public const ushort BackMassage = 3;
        public const ushort BellyBreathing = 4;
        public const ushort BridgeWithBall = 5;
        public const ushort DiamondLegCrunch = 6;
        public const ushort DiamondLegLift = 7;
        public const ushort EightPointShoulderOpener = 8;
        public const ushort FootRolling = 9;
        public const ushort Footwork = 10;
        public const ushort FootworkOnDisc = 11;
        public const ushort ForwardFold = 12;
        public const ushort FrogWithBand = 13;
        public const ushort HalfRollUp = 14;
        public const ushort HamstringCurl = 15;
        public const ushort HamstringStretch = 16;
        public const ushort HipStretch = 17;
        public const ushort HugATreeWithBallBandAndWeight = 18;
        public const ushort KneeCircles = 19;
        public const ushort KneeFoldsOnDisc = 20;
        public const ushort LateralFlexion = 21;
        public const ushort LegStretchWithBand = 22;
        public const ushort LegStretchWithLegCircles = 23;
        public const ushort LowerLiftOnDisc = 24;
        public const ushort LungeSquat = 25;
        public const ushort LungesWithKneeLift = 26;
        public const ushort MermaidStretch = 27;
        public const ushort NeutralPelvicPosition = 28;
        public const ushort PelvicClocksOnDisc = 29;
        public const ushort PilatesPlieSquatsParallelTurnedOutFlatAndHeelsWithChair = 30;
        public const ushort PiriformisStretch = 31;
        public const ushort PlankKneeCrosses = 32;
        public const ushort PlankKneePulls = 33;
        public const ushort PlankUpDowns = 34;
        public const ushort PrayerMudra = 35;
        public const ushort PsoasLungeStretch = 36;
        public const ushort RibcageBreathing = 37;
        public const ushort RollDown = 38;
        public const ushort RollUpWithWeightAndBand = 39;
        public const ushort Saw = 40;
        public const ushort ScapularStabilization = 41;
        public const ushort ScissorsOnDisc = 42;
        public const ushort SeatedHipStretchup = 43;
        public const ushort SeatedTwist = 44;
        public const ushort ShavingTheHeadWithBallBandAndWeight = 45;
        public const ushort SpinalTwist = 46;
        public const ushort SpinalTwistStretch = 47;
        public const ushort SpineStretchForward = 48;
        public const ushort SquatOpenArmTwistPose = 49;
        public const ushort SquatsWithBall = 50;
        public const ushort StandAndHang = 51;
        public const ushort StandingSideStretch = 52;
        public const ushort StandingSingleLegForwardBendWithItBandOpener = 53;
        public const ushort StraightLegCrunchWithLegLift = 54;
        public const ushort StraightLegCrunchWithLegLiftWithBall = 55;
        public const ushort StraightLegCrunchWithLegsCrossed = 56;
        public const ushort StraightLegCrunchWithLegsCrossedWithBall = 57;
        public const ushort StraightLegDiagonalCrunch = 58;
        public const ushort StraightLegDiagonalCrunchWithBall = 59;
        public const ushort TailboneCurl = 60;
        public const ushort ThroatLock = 61;
        public const ushort TickTockSideRoll = 62;
        public const ushort Twist = 63;
        public const ushort VLegCrunches = 64;
        public const ushort VSit = 65;
        public const ushort ForwardFoldWheelchair = 66;
        public const ushort ForwardFoldPlusWheelchair = 67;
        public const ushort ArmCirclesLowForwardWheelchair = 68;
        public const ushort ArmCirclesMidForwardWheelchair = 69;
        public const ushort ArmCirclesHighForwardWheelchair = 70;
        public const ushort ArmCirclesLowBackwardWheelchair = 71;
        public const ushort ArmCirclesMidBackwardWheelchair = 72;
        public const ushort ArmCirclesHighBackwardWheelchair = 73;
        public const ushort CoreTwistsWheelchair = 74;
        public const ushort ArmRaiseWheelchair = 75;
        public const ushort ChestExpandWheelchair = 76;
        public const ushort ArmExtendWheelchair = 77;
        public const ushort ForwardBendWheelchair = 78;
        public const ushort ToeTouchWheelchair = 79;
        public const ushort ExtendedToeTouchWheelchair = 80;
        public const ushort SeatedArmCircles = 81;
        public const ushort TrunkRotations = 82;
        public const ushort SeatedTrunkRotations = 83;
        public const ushort ToeTouch = 84;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

