#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile OlympicLiftExerciseName type as a class
    /// </summary>
    public static class OlympicLiftExerciseName 
    {
        public const ushort BarbellHangPowerClean = 0;
        public const ushort BarbellHangSquatClean = 1;
        public const ushort BarbellPowerClean = 2;
        public const ushort BarbellPowerSnatch = 3;
        public const ushort BarbellSquatClean = 4;
        public const ushort CleanAndJerk = 5;
        public const ushort BarbellHangPowerSnatch = 6;
        public const ushort BarbellHangPull = 7;
        public const ushort BarbellHighPull = 8;
        public const ushort BarbellSnatch = 9;
        public const ushort BarbellSplitJerk = 10;
        public const ushort Clean = 11;
        public const ushort DumbbellClean = 12;
        public const ushort DumbbellHangPull = 13;
        public const ushort OneHandDumbbellSplitSnatch = 14;
        public const ushort PushJerk = 15;
        public const ushort SingleArmDumbbellSnatch = 16;
        public const ushort SingleArmHangSnatch = 17;
        public const ushort SingleArmKettlebellSnatch = 18;
        public const ushort SplitJerk = 19;
        public const ushort SquatCleanAndJerk = 20;
        public const ushort DumbbellHangSnatch = 21;
        public const ushort DumbbellPowerCleanAndJerk = 22;
        public const ushort DumbbellPowerCleanAndPushPress = 23;
        public const ushort DumbbellPowerCleanAndStrictPress = 24;
        public const ushort DumbbellSnatch = 25;
        public const ushort MedicineBallClean = 26;
        public const ushort CleanAndPress = 27;
        public const ushort Snatch = 28;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

