#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile RunExerciseName type as a class
    /// </summary>
    public static class RunExerciseName 
    {
        public const ushort Run = 0;
        public const ushort Walk = 1;
        public const ushort Jog = 2;
        public const ushort Sprint = 3;
        public const ushort RunOrWalk = 4;
        public const ushort SpeedWalk = 5;
        public const ushort WarmUp = 6;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

