#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SaxonGradingScale type as an enum
    /// </summary>
    public enum SaxonGradingScale : byte
    {
        I = 0,
        II = 1,
        III = 2,
        IV = 3,
        V = 4,
        VI = 5,
        VIIA = 6,
        VIIB = 7,
        VIIC = 8,
        VIIIA = 9,
        VIIIB = 10,
        VIIIC = 11,
        IXA = 12,
        IXB = 13,
        IXC = 14,
        XA = 15,
        XB = 16,
        XC = 17,
        XIA = 18,
        XIB = 19,
        XIC = 20,
        XIIA = 21,
        XIIB = 22,
        XIIC = 23,
        Invalid = 0xFF


    }
}

