#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ShrugExerciseName type as a class
    /// </summary>
    public static class ShrugExerciseName 
    {
        public const ushort BarbellJumpShrug = 0;
        public const ushort BarbellShrug = 1;
        public const ushort BarbellUprightRow = 2;
        public const ushort BehindTheBackSmithMachineShrug = 3;
        public const ushort DumbbellJumpShrug = 4;
        public const ushort DumbbellShrug = 5;
        public const ushort DumbbellUprightRow = 6;
        public const ushort InclineDumbbellShrug = 7;
        public const ushort OverheadBarbellShrug = 8;
        public const ushort OverheadDumbbellShrug = 9;
        public const ushort ScaptionAndShrug = 10;
        public const ushort ScapularRetraction = 11;
        public const ushort SerratusChairShrug = 12;
        public const ushort WeightedSerratusChairShrug = 13;
        public const ushort SerratusShrug = 14;
        public const ushort WeightedSerratusShrug = 15;
        public const ushort WideGripJumpShrug = 16;
        public const ushort WideGripBarbellShrug = 17;
        public const ushort BehindTheBackShrug = 18;
        public const ushort DumbbellShrugWheelchair = 19;
        public const ushort ShrugWheelchair = 20;
        public const ushort ShrugArmDownWheelchair = 21;
        public const ushort ShrugArmMidWheelchair = 22;
        public const ushort ShrugArmUpWheelchair = 23;
        public const ushort UprightRow = 24;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

