#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile Sport type as an enum
    /// </summary>
    public enum Sport : byte
    {
        Generic = 0,
        Running = 1,
        Cycling = 2,
        Transition = 3,
        FitnessEquipment = 4,
        Swimming = 5,
        Basketball = 6,
        Soccer = 7,
        Tennis = 8,
        AmericanFootball = 9,
        Training = 10,
        Walking = 11,
        CrossCountrySkiing = 12,
        AlpineSkiing = 13,
        Snowboarding = 14,
        Rowing = 15,
        Mountaineering = 16,
        Hiking = 17,
        Multisport = 18,
        Paddling = 19,
        Flying = 20,
        EBiking = 21,
        Motorcycling = 22,
        Boating = 23,
        Driving = 24,
        Golf = 25,
        HangGliding = 26,
        HorsebackRiding = 27,
        Hunting = 28,
        Fishing = 29,
        InlineSkating = 30,
        RockClimbing = 31,
        Sailing = 32,
        IceSkating = 33,
        SkyDiving = 34,
        Snowshoeing = 35,
        Snowmobiling = 36,
        StandUpPaddleboarding = 37,
        Surfing = 38,
        Wakeboarding = 39,
        WaterSkiing = 40,
        Kayaking = 41,
        Rafting = 42,
        Windsurfing = 43,
        Kitesurfing = 44,
        Tactical = 45,
        Jumpmaster = 46,
        Boxing = 47,
        FloorClimbing = 48,
        Baseball = 49,
        Diving = 53,
        Shooting = 56,
        WinterSport = 58,
        Grinding = 59,
        Hiit = 62,
        VideoGaming = 63,
        Racket = 64,
        WheelchairPushWalk = 65,
        WheelchairPushRun = 66,
        Meditation = 67,
        ParaSport = 68,
        DiscGolf = 69,
        TeamSport = 70,
        Cricket = 71,
        Rugby = 72,
        Hockey = 73,
        Lacrosse = 74,
        Volleyball = 75,
        WaterTubing = 76,
        Wakesurfing = 77,
        WaterSport = 78,
        Archery = 79,
        MixedMartialArts = 80,
        MotorSports = 81,
        Snorkeling = 82,
        Dance = 83,
        JumpRope = 84,
        PoolApnea = 85,
        Mobility = 86,
        Geocaching = 87,
        Canoeing = 88,
        All = 254,
        Invalid = 0xFF


    }
}

