#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SportEvent type as an enum
    /// </summary>
    public enum SportEvent : byte
    {
        Uncategorized = 0,
        Geocaching = 1,
        Fitness = 2,
        Recreation = 3,
        Race = 4,
        SpecialEvent = 5,
        Training = 6,
        Transportation = 7,
        Touring = 8,
        Invalid = 0xFF


    }
}

