#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SwimStroke type as an enum
    /// </summary>
    public enum SwimStroke : byte
    {
        Freestyle = 0,
        Backstroke = 1,
        Breaststroke = 2,
        Butterfly = 3,
        Drill = 4,
        Mixed = 5,
        Im = 6,
        Invalid = 0xFF


    }
}

