#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile UiaaGradingScale type as an enum
    /// </summary>
    public enum UiaaGradingScale : byte
    {
        I = 0,
        II = 1,
        III = 2,
        IVMinus = 3,
        IV = 4,
        IVPlus = 5,
        VMinus = 6,
        V = 7,
        VPlus = 8,
        VIMinus = 9,
        VI = 10,
        VIPlus = 11,
        VIIMinus = 12,
        VII = 13,
        VIIPlus = 14,
        VIIIMinus = 15,
        VIII = 16,
        VIIIPlus = 17,
        IXMinus = 18,
        IX = 19,
        IXPlus = 20,
        XMinus = 21,
        X = 22,
        XPlus = 23,
        XIMinus = 24,
        XI = 25,
        XIPlus = 26,
        XIIMinus = 27,
        Invalid = 0xFF


    }
}

