#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile UserLocalId type as a class
    /// </summary>
    public static class UserLocalId 
    {
        public const ushort LocalMin = 0x0000;
        public const ushort LocalMax = 0x000F;
        public const ushort StationaryMin = 0x0010;
        public const ushort StationaryMax = 0x00FF;
        public const ushort PortableMin = 0x0100;
        public const ushort PortableMax = 0xFFFE;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

