#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile YdsGradingScale type as an enum
    /// </summary>
    public enum YdsGradingScale : byte
    {
        _51 = 0,
        _52 = 1,
        _53 = 2,
        _54 = 3,
        _55 = 4,
        _56 = 5,
        _57 = 6,
        _58 = 7,
        _59 = 8,
        _510 = 9,
        _510a = 10,
        _510b = 11,
        _510c = 12,
        _510d = 13,
        _511 = 14,
        _511a = 15,
        _511b = 16,
        _511c = 17,
        _511d = 18,
        _512 = 19,
        _512a = 20,
        _512b = 21,
        _512c = 22,
        _512d = 23,
        _513 = 24,
        _513a = 25,
        _513b = 26,
        _513c = 27,
        _513d = 28,
        _514 = 29,
        _514a = 30,
        _514b = 31,
        _514c = 32,
        _514d = 33,
        _515 = 34,
        _515a = 35,
        _515b = 36,
        _515c = 37,
        _515d = 38,
        _51Minus = 39,
        _51Plus = 40,
        _52Minus = 41,
        _52Plus = 42,
        _53Minus = 43,
        _53Plus = 44,
        _54Minus = 45,
        _54Plus = 46,
        _55Minus = 47,
        _55Plus = 48,
        _56Minus = 49,
        _56Plus = 50,
        _57Minus = 51,
        _57Plus = 52,
        _58Minus = 53,
        _58Plus = 54,
        _59Minus = 55,
        _59Plus = 56,
        _510Minus = 57,
        _510Plus = 58,
        _511Minus = 59,
        _511Plus = 60,
        _512Minus = 61,
        _512Plus = 62,
        _513Minus = 63,
        _513Plus = 64,
        _514Minus = 65,
        _514Plus = 66,
        _515Minus = 67,
        _515Plus = 68,
        Invalid = 0xFF


    }
}

