#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using System.Linq;

namespace Dynastream.Fit
{
	/// <summary>
	/// Implements the AntChannelId profile message.
	/// </summary>
	public class AntChannelIdMesg : Mesg
	{
		#region Fields
		#endregion

		/// <summary>
		/// Field Numbers for <see cref="AntChannelIdMesg"/>
		/// </summary>
		public sealed class FieldDefNum
		{
			public const byte ChannelNumber = 0;
			public const byte DeviceType = 1;
			public const byte DeviceNumber = 2;
			public const byte TransmissionType = 3;
			public const byte DeviceIndex = 4;
			public const byte Invalid = Fit.FieldNumInvalid;
		}

		#region Constructors
		public AntChannelIdMesg() : base(Profile.GetMesg(MesgNum.AntChannelId))
		{
		}

		public AntChannelIdMesg(Mesg mesg) : base(mesg)
		{
		}
		#endregion // Constructors

		#region Methods
		///<summary>
		/// Retrieves the ChannelNumber field</summary>
		/// <returns>Returns nullable byte representing the ChannelNumber field</returns>
		public byte? ChannelNumber
		{
			get
			{
				Object val = GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(0, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the DeviceType field</summary>
		/// <returns>Returns nullable byte representing the DeviceType field</returns>
		public byte? DeviceType
		{
			get
			{
				Object val = GetFieldValue(1, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(1, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the DeviceNumber field</summary>
		/// <returns>Returns nullable ushort representing the DeviceNumber field</returns>
		public ushort? DeviceNumber
		{
			get
			{
				Object val = GetFieldValue(2, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToUInt16(val));

			}
			set
			{
				SetFieldValue(2, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the TransmissionType field</summary>
		/// <returns>Returns nullable byte representing the TransmissionType field</returns>
		public byte? TransmissionType
		{
			get
			{
				Object val = GetFieldValue(3, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(3, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the DeviceIndex field</summary>
		/// <returns>Returns nullable byte representing the DeviceIndex field</returns>
		public byte? DeviceIndex
		{
			get
			{
				Object val = GetFieldValue(4, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(4, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		#endregion // Methods
	} // Class
} // namespace
