#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using System.Linq;

namespace Dynastream.Fit
{
	/// <summary>
	/// Implements the ExdScreenConfiguration profile message.
	/// </summary>
	public class ExdScreenConfigurationMesg : Mesg
	{
		#region Fields
		#endregion

		/// <summary>
		/// Field Numbers for <see cref="ExdScreenConfigurationMesg"/>
		/// </summary>
		public sealed class FieldDefNum
		{
			public const byte ScreenIndex = 0;
			public const byte FieldCount = 1;
			public const byte Layout = 2;
			public const byte ScreenEnabled = 3;
			public const byte Invalid = Fit.FieldNumInvalid;
		}

		#region Constructors
		public ExdScreenConfigurationMesg() : base(Profile.GetMesg(MesgNum.ExdScreenConfiguration))
		{
		}

		public ExdScreenConfigurationMesg(Mesg mesg) : base(mesg)
		{
		}
		#endregion // Constructors

		#region Methods
		///<summary>
		/// Retrieves the ScreenIndex field</summary>
		/// <returns>Returns nullable byte representing the ScreenIndex field</returns>
		public byte? ScreenIndex
		{
			get
			{
				Object val = GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(0, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the FieldCount field
		/// Comment: number of fields in screen</summary>
		/// <returns>Returns nullable byte representing the FieldCount field</returns>
		public byte? FieldCount
		{
			get
			{
				Object val = GetFieldValue(1, 0, Fit.SubfieldIndexMainField);
				if (val == null)
				{
					return null;
				}

				return (Convert.ToByte(val));

			}
			set
			{
				SetFieldValue(1, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the Layout field</summary>
		/// <returns>Returns nullable ExdLayout enum representing the Layout field</returns>
		public ExdLayout? Layout
		{
			get
			{
				object obj = GetFieldValue(2, 0, Fit.SubfieldIndexMainField);
				ExdLayout? value = obj == null ? (ExdLayout?)null : (ExdLayout)obj;
				return value;
			}
			set
			{
				SetFieldValue(2, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		///<summary>
		/// Retrieves the ScreenEnabled field</summary>
		/// <returns>Returns nullable Bool enum representing the ScreenEnabled field</returns>
		public Bool? ScreenEnabled
		{
			get
			{
				object obj = GetFieldValue(3, 0, Fit.SubfieldIndexMainField);
				Bool? value = obj == null ? (Bool?)null : (Bool)obj;
				return value;
			}
			set
			{
				SetFieldValue(3, 0, value, Fit.SubfieldIndexMainField);
			}
		}

		#endregion // Methods
	} // Class
} // namespace
