#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using System.Linq;

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the NapEvent profile message.
    /// </summary>
    public class NapEventMesg : Mesg
    {
        #region Fields
        #endregion

        /// <summary>
        /// Field Numbers for <see cref="NapEventMesg"/>
        /// </summary>
        public sealed class FieldDefNum
        {
            public const byte MessageIndex = 254;
            public const byte Timestamp = 253;
            public const byte StartTime = 0;
            public const byte StartTimezoneOffset = 1;
            public const byte EndTime = 2;
            public const byte EndTimezoneOffset = 3;
            public const byte Feedback = 4;
            public const byte IsDeleted = 5;
            public const byte Source = 6;
            public const byte UpdateTimestamp = 7;
            public const byte Invalid = Fit.FieldNumInvalid;
        }

        #region Constructors
        public NapEventMesg() : base(Profile.GetMesg(MesgNum.NapEvent))
        {
        }

        public NapEventMesg(Mesg mesg) : base(mesg)
        {
        }
        #endregion // Constructors

        #region Methods
        ///<summary>
        /// Retrieves the MessageIndex field</summary>
        /// <returns>Returns nullable ushort representing the MessageIndex field</returns>
        public ushort? GetMessageIndex()
        {
            Object val = GetFieldValue(254, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return (Convert.ToUInt16(val));
            
        }

        /// <summary>
        /// Set MessageIndex field</summary>
        /// <param name="messageIndex_">Nullable field value to be set</param>
        public void SetMessageIndex(ushort? messageIndex_)
        {
            SetFieldValue(254, 0, messageIndex_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the Timestamp field</summary>
        /// <returns>Returns DateTime representing the Timestamp field</returns>
        public DateTime GetTimestamp()
        {
            Object val = GetFieldValue(253, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return TimestampToDateTime(Convert.ToUInt32(val));
            
        }

        /// <summary>
        /// Set Timestamp field</summary>
        /// <param name="timestamp_">Nullable field value to be set</param>
        public void SetTimestamp(DateTime timestamp_)
        {
            SetFieldValue(253, 0, timestamp_.GetTimeStamp(), Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the StartTime field
        /// Units: seconds</summary>
        /// <returns>Returns DateTime representing the StartTime field</returns>
        public DateTime GetStartTime()
        {
            Object val = GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return TimestampToDateTime(Convert.ToUInt32(val));
            
        }

        /// <summary>
        /// Set StartTime field
        /// Units: seconds</summary>
        /// <param name="startTime_">Nullable field value to be set</param>
        public void SetStartTime(DateTime startTime_)
        {
            SetFieldValue(0, 0, startTime_.GetTimeStamp(), Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the StartTimezoneOffset field
        /// Units: minutes</summary>
        /// <returns>Returns nullable short representing the StartTimezoneOffset field</returns>
        public short? GetStartTimezoneOffset()
        {
            Object val = GetFieldValue(1, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return (Convert.ToInt16(val));
            
        }

        /// <summary>
        /// Set StartTimezoneOffset field
        /// Units: minutes</summary>
        /// <param name="startTimezoneOffset_">Nullable field value to be set</param>
        public void SetStartTimezoneOffset(short? startTimezoneOffset_)
        {
            SetFieldValue(1, 0, startTimezoneOffset_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the EndTime field
        /// Units: seconds</summary>
        /// <returns>Returns DateTime representing the EndTime field</returns>
        public DateTime GetEndTime()
        {
            Object val = GetFieldValue(2, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return TimestampToDateTime(Convert.ToUInt32(val));
            
        }

        /// <summary>
        /// Set EndTime field
        /// Units: seconds</summary>
        /// <param name="endTime_">Nullable field value to be set</param>
        public void SetEndTime(DateTime endTime_)
        {
            SetFieldValue(2, 0, endTime_.GetTimeStamp(), Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the EndTimezoneOffset field
        /// Units: minutes</summary>
        /// <returns>Returns nullable short representing the EndTimezoneOffset field</returns>
        public short? GetEndTimezoneOffset()
        {
            Object val = GetFieldValue(3, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return (Convert.ToInt16(val));
            
        }

        /// <summary>
        /// Set EndTimezoneOffset field
        /// Units: minutes</summary>
        /// <param name="endTimezoneOffset_">Nullable field value to be set</param>
        public void SetEndTimezoneOffset(short? endTimezoneOffset_)
        {
            SetFieldValue(3, 0, endTimezoneOffset_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the Feedback field</summary>
        /// <returns>Returns nullable NapPeriodFeedback enum representing the Feedback field</returns>
        public NapPeriodFeedback? GetFeedback()
        {
            object obj = GetFieldValue(4, 0, Fit.SubfieldIndexMainField);
            NapPeriodFeedback? value = obj == null ? (NapPeriodFeedback?)null : (NapPeriodFeedback)obj;
            return value;
        }

        /// <summary>
        /// Set Feedback field</summary>
        /// <param name="feedback_">Nullable field value to be set</param>
        public void SetFeedback(NapPeriodFeedback? feedback_)
        {
            SetFieldValue(4, 0, feedback_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the IsDeleted field</summary>
        /// <returns>Returns nullable Bool enum representing the IsDeleted field</returns>
        public Bool? GetIsDeleted()
        {
            object obj = GetFieldValue(5, 0, Fit.SubfieldIndexMainField);
            Bool? value = obj == null ? (Bool?)null : (Bool)obj;
            return value;
        }

        /// <summary>
        /// Set IsDeleted field</summary>
        /// <param name="isDeleted_">Nullable field value to be set</param>
        public void SetIsDeleted(Bool? isDeleted_)
        {
            SetFieldValue(5, 0, isDeleted_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the Source field</summary>
        /// <returns>Returns nullable NapSource enum representing the Source field</returns>
        public NapSource? GetSource()
        {
            object obj = GetFieldValue(6, 0, Fit.SubfieldIndexMainField);
            NapSource? value = obj == null ? (NapSource?)null : (NapSource)obj;
            return value;
        }

        /// <summary>
        /// Set Source field</summary>
        /// <param name="source_">Nullable field value to be set</param>
        public void SetSource(NapSource? source_)
        {
            SetFieldValue(6, 0, source_, Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the UpdateTimestamp field
        /// Comment: The timestamp representing when this nap event was last updated</summary>
        /// <returns>Returns DateTime representing the UpdateTimestamp field</returns>
        public DateTime GetUpdateTimestamp()
        {
            Object val = GetFieldValue(7, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return TimestampToDateTime(Convert.ToUInt32(val));
            
        }

        /// <summary>
        /// Set UpdateTimestamp field
        /// Comment: The timestamp representing when this nap event was last updated</summary>
        /// <param name="updateTimestamp_">Nullable field value to be set</param>
        public void SetUpdateTimestamp(DateTime updateTimestamp_)
        {
            SetFieldValue(7, 0, updateTimestamp_.GetTimeStamp(), Fit.SubfieldIndexMainField);
        }
        
        #endregion // Methods
    } // Class
} // namespace
