#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.188.0Release
// Tag = production/release/21.188.0-0-g55050f8
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using System.Linq;

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the SleepDisruptionOvernightSeverity profile message.
    /// </summary>
    public class SleepDisruptionOvernightSeverityMesg : Mesg
    {
        #region Fields
        #endregion

        /// <summary>
        /// Field Numbers for <see cref="SleepDisruptionOvernightSeverityMesg"/>
        /// </summary>
        public sealed class FieldDefNum
        {
            public const byte Timestamp = 253;
            public const byte Severity = 0;
            public const byte Invalid = Fit.FieldNumInvalid;
        }

        #region Constructors
        public SleepDisruptionOvernightSeverityMesg() : base(Profile.GetMesg(MesgNum.SleepDisruptionOvernightSeverity))
        {
        }

        public SleepDisruptionOvernightSeverityMesg(Mesg mesg) : base(mesg)
        {
        }
        #endregion // Constructors

        #region Methods
        ///<summary>
        /// Retrieves the Timestamp field</summary>
        /// <returns>Returns DateTime representing the Timestamp field</returns>
        public DateTime GetTimestamp()
        {
            Object val = GetFieldValue(253, 0, Fit.SubfieldIndexMainField);
            if(val == null)
            {
                return null;
            }

            return TimestampToDateTime(Convert.ToUInt32(val));
            
        }

        /// <summary>
        /// Set Timestamp field</summary>
        /// <param name="timestamp_">Nullable field value to be set</param>
        public void SetTimestamp(DateTime timestamp_)
        {
            SetFieldValue(253, 0, timestamp_.GetTimeStamp(), Fit.SubfieldIndexMainField);
        }
        
        ///<summary>
        /// Retrieves the Severity field</summary>
        /// <returns>Returns nullable SleepDisruptionSeverity enum representing the Severity field</returns>
        public SleepDisruptionSeverity? GetSeverity()
        {
            object obj = GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
            SleepDisruptionSeverity? value = obj == null ? (SleepDisruptionSeverity?)null : (SleepDisruptionSeverity)obj;
            return value;
        }

        /// <summary>
        /// Set Severity field</summary>
        /// <param name="severity_">Nullable field value to be set</param>
        public void SetSeverity(SleepDisruptionSeverity? severity_)
        {
            SetFieldValue(0, 0, severity_, Fit.SubfieldIndexMainField);
        }
        
        #endregion // Methods
    } // Class
} // namespace
